services:
  app:
    container_name: ts-node-starter
    image: node:18.14.0
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    ports:
      - 3030:3030